services:
    vms-bot:
        image: golang:1.24-alpine3.20
        container_name: vms-bot
        volumes:
            - ./app:/go/src/app
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - 8022:8282
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
